### ISSUE TITLE
Name Change / Breaking SSO

### ISSUE THREAD

**Issue by jbreed03** [MSOpenTech/o365-moodle#2290]
Hi friends! 

I'm having an issue where a user will need a name change via O365. After the UPN is updated in Moodle and the email and UPN are updated in O365 they are no longer able to sign into Moodle via SSO. What am I missing or doing wrong? Any help would be appreciated!

**Comment by AntonT76** [comment]
Dear @jbreed03 ,
I think the reason is the change of the UPN. As a result, the token of the user no longer fits. You can try to disconnect and reconnect the user. As Moodle Admin you can find it here:
- Website-Administration / Plugins / local plugins / Microsoft 365-Integration
- go to tab "Advanced" and "Manage User Connections"
- search user and disconnect and reconnect the user

hope this will help.
br Anton
