### ISSUE TITLE
Moodle LTI O365 connection with enterprise licence?

### ISSUE THREAD

**Issue by francopantoja** [MSOpenTech/o365-moodle#2355]
Dear
We are currently getting this error 
"You need an educator or student licence to use Teams for Education. Try asking your IT administrator to assign you the correct licence."
It is possible to use with an Enterprise 365 License?

Thanks

**Comment by weilai-irl** [comment]
Hi @francopantoja 

I confirm the issue is thrown by Microsoft Teams, rather than by the plugins in Moodle. Could you confirm the following details to help us providing more assistance please:

- The version of Moodle and the Microsoft plugins (auth_oidc and local_o365). 
- Whether your Microsoft tenant has the one of the following server plans:
 1. SCHOOL_DATA_SYNC_P1 (c33802dd-1b50-4b9a-8bb9-f13d2cdeadac)
 2. SCHOOL_DATA_SYNC_P2 (500b6a2a-7a50-4f40-b5f9-160e5b8c2f48)
- When exactly did you see the error, is it when trying to create the Teams, or is it after the Teams are created, but when some users try to access the Teams.

For a bit of background, the integration checks automatically to see if the two service plans named above are present in the tenant, and would use the Education Graph endpoints to create education group/team; otherwise the standard Team endpoints are used.

Regards,
Lai

**Comment by mmast-msft** [comment]
The Teams LTI tools require users to have education licenses assigned. Additionally, they only work with "Class" teams that are only available in EDU tenants.
