### ISSUE TITLE
SharePoint site not created

### ISSUE THREAD

**Issue by stripe4** [MSOpenTech/o365-moodle#44]
If I type in a SharePoint site URL, Moodle successfully detects whether the site exists or not (blue or green message). After typing in a new SharePoint site URL and saving changes, I receive a message "Moodle is setting up this SharePoint site". The cron job runs successfully, too:

Server Time: Tue, 02 Jun 2015 12:12:08 +0300

Execute adhoc task: local_o365\task\sharepointinit
... started 12:12:12. Current memory use 4.5MB.
Created parent site
... used 6 dbqueries
... used 7.1267318725586 seconds
Adhoc task complete: local_o365\task\sharepointinit
Cron script completed correctly
Cron completed at 12:12:19. Memory used 5.6MB.
Execution took 10.851464 seconds

When I return to Microsoft Office 365 Integration plugin settings page, "SharePoint Link" section informs that "Moodle is connected to this SharePoint site."

Unfortunately this is not true because the SharePoint site has not been created.

local_o365 plugin version and release:
2015012716, 28.0.0.9

**Comment by jamesmcq** [comment]
Hi stripe4,

A couple questions:
- What do you see when you visit the entered SharePoint site?
- Have you set the system API user?
- What do you see when visiting the health check? (Accessible from the same settings page)

Thanks!

**Comment by stripe4** [comment]
Hi James,

When I visit the SharePoint site, I receive HTTP 404 error (because Moodle did not create it), and the site is not present in the site content section of the parent site.
Yes, the system API user is set (I use global admin account).
Health check returns "Moodle can communicate with Office 365 as the system API user."

Other sections on Microsoft Office 365 Integration plugin settings page are highlighted in green color, only Application Permissions section reports that Unified API is not present, although I doubt that is the issue.
The API user is able (has the necessary permissions) to create sites within SharePoint.

**Comment by jamesmcq** [comment]
What site are you entering for the SharePoint site URI? (You can replace the domain with a placeholder for the sake of privacy, just looking for everything after that).

**Comment by stripe4** [comment]
I use https://mytenant.sharepoint.com/moodle
I have also tried a different site collection under the same tenant, e.g. https://mytenant.sharepoint.com/sites/mr/moodle and the result is the same - site is not created.
Just to test things out, I have also tried to input https://notmytenant.sharepoint.com/moodle and the plugin detects that this is not my tenant, and reports "This is not a usable SharePoint site."

**Comment by grant007** [comment]
I am experiencing the same issue. I cannot get a SharePoint site to be created. I have even pre-created the site but the Office365 Integration never makes use of the site. Manually running the cron job I did capture the following output that appears to have an error.

Execute adhoc task: local_o365\task\sharepointaccesssync
... started 12:27:43. Current memory use 40.8MB.
... used 12 dbqueries
... used 62.978773832321 seconds
Adhoc task failed: local_o365\task\sharepointaccesssync,Error in API call.
Execute adhoc task: local_o365\task\sharepointaccesssync
... started 12:28:46. Current memory use 41.6MB.
... used 9 dbqueries
... used 2.5951528549194 seconds
Adhoc task failed: local_o365\task\sharepointaccesssync,Error writing to database
Cron script completed correctly
Cron completed at 12:28:48. Memory used 41.7MB.
Execution took 74.317336 seconds

I have two separate and distinct Moodle instances and the issue is effecting both. And a few weeks prior when I was doing proof of concept testing, sites were being created. I deleted the testing site collection from SharePoint and then pointed the Office365 Integration to a different location and that is when I noticed sites were NOT being created. I have tried multiple site collections i.e. /sites/courses, /teams/courses and like I said above, I have tried both pre-creating the sites and not. 

Please advise on how I can further investigate and debug this.

**Comment by jamesmcq** [comment]
@grant007 @stripe4 Can you list the permissions you have enabled for "Office365 SharePoint Online" in Azure?

**Comment by grant007** [comment]
see attached

[image: Inline image 1]

On Thu, Jul 30, 2015 at 11:45 AM, James McQuillan <notifications@github.com>
wrote:

> @grant007 <https://github.com/grant007> @stripe4
> <https://github.com/stripe4> Can you list the permissions you have
> enabled for "Office365 SharePoint Online" in Azure?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MSOpenTech/o365-moodle/issues/44#issuecomment-126374868>
> .
>



-- 
Grant Stone

**Comment by jamesmcq** [comment]
@grant007 Image didn't come through, I guess github doesn't get attached images on email replies.

**Comment by grant007** [comment]
Application Permissions: 0...
none

Delegate Permissions: 6...
Read items in all Site collections
Read and write items in all site collections
Read and write items and lists in all site collections
Have full control of all site collections
Read user files
Read and Write user files

-grant

On Thu, Jul 30, 2015 at 4:59 PM, James McQuillan <notifications@github.com>
wrote:

> @grant007 <https://github.com/grant007> Image didn't come through, I
> guess github doesn't get attached images on email replies.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MSOpenTech/o365-moodle/issues/44#issuecomment-126485632>
> .
>



-- 
Grant Stone

**Comment by jamesmcq** [comment]
Hi Grant, pre-creating the sites won't work because Moodle needs to know the IDs of the sites to communicate with them - it gets these when it creates the sites. 

@stripe4 @grant007 Can you either post or email (james.mcquillan@remote-learner.net) me the "shortname" of your Moodle site? This is the one variable that may be causing issues. and @grant007 you mentioned that you had sharepoint working on a previous test site, can you send me the shortname of that site as well?

Thanks all

**Comment by alight-eskillz** [comment]
I'm experiencing the issue of the Moodle SharePoint site never getting created, and the plugin still shows "Moodle is setting up this SharePoint site".  I've successfully set up everything except what I posted in #50 (not sure if simply missing the AAD UserProfile.Read permission would prevent SharePoint site creation).

@jamesmcq, I will also email you the short name of our Moodle site.  I'm brand-new to Moodle and I don't have any PHP experience, so I'm not sure how to collect the information others have posted (especially since I'm on a GoDaddy shared host for now...might migrate to a full-fledged Azure VM if we can get this to work), but I am an experienced full-stack software developer, so please let me know what info you'd like me to collect (if any) and how.

Thanks.

**Comment by jamesmcq** [comment]
Hi Andre - has your site's cron run? SharePoint is set up during the Moodle cron. If so, have you seen any errors/messages/etc?

What version of local_o365 are you using? If you see the "record debug messages" setting on the Office 365 integration local plugin settings page, try enabling that and run the cron again. This will record debug messages to the Moodle log, viewable from Site Administration > Reports > Logs > Get these logs

**Comment by alight-eskillz** [comment]
James, thank you.  I didn't set up the cron job on GoDaddy (didn't realize that was necessary...as I said, I'm brand-new to Moodle and inexperienced with PHP).  After running the Cron job manually, the site was created and a sub-site was added for a test course.  Now, I just need to figure out how to set up an automated cron job...

**Comment by jamesmcq** [comment]
I've updated the SharePoint site creation code with the latest release. Can you update and let me know if the issue persists?

**Comment by jamesmcq** [comment]
Going to close this issue as most SharePoint site creation issues should be resolved. If you try out the newest release and are still having problems with SharePoint please create a new issue.
