### ISSUE TITLE
OneDrive permission problem with MyFiles functionality

### ISSUE THREAD

**Issue by eabcdev** [MSOpenTech/o365-moodle#56]
Hi Team,

I have Moodle 2.7 with latest plugins version. We have all delegated permissions enabled in Azure (25 for unified API and 11 for sharepoint online. 

When the user tries to access to MyFiles folder:

![image](https://cloud.githubusercontent.com/assets/14235324/10608551/e7d8bdae-7715-11e5-862a-f53b99e208b8.png)

It gets an API error (Error in API call) and the reports debug shows two kind of messages:

API failure	local_o365\rest\unified::get_files:324: Bad response received Data: (string)Resource not found for the segment 'files'.

API failure	local_o365\rest\unified::get_files:324: Error response received. Data: Array ( [code] => -2147024891, System.UnauthorizedAccessException [message] => Access denied. You do not have permission to perform this action or access this resource. )

Do you know how can we solve this?
best

**Comment by jamesmcq** [comment]
Hi eabcdev,

This is due to a recent change with the Office Unified API. I'm working on an update but until then I recommend removing the unified API from your application in Azure. After you've removed it from Azure, run the "Azure Setup" tool in the Office 365 integration local plugin settings page. This should disable the unified API and cause the plugins to use the original Office 365 API, which should work fine. Please let me know if this resolves the issue for you.

Thanks,
- James

**Comment by eabcdev** [comment]
Thanks James! It does not affect other functionality present in the integration?
best,
Gabriel

**Comment by jamesmcq** [comment]
The Unified API is a new API that replaced the old application-specific APIs, but it provides largely the same functionality. It seems to be causing some issues so I'm recommending against it for now, however it will eventually replace the old API. The one feature missing from the older API is unified user groups, used by the "Create user groups" setting. I am releasing a new version of the plugins later today that will better handle the unified API that you'll want to update to if the user groups setting is essential.
